// Code generated by scripts/gen_obs.py; DO NOT EDIT.
// Edit packages/schema/observability.json and run `make gen`.
//
// This file holds the vocabulary only. The handler that applies it, and the
// reasoning for wrapping slog.Handler rather than using ReplaceAttr, are in
// redact.go.

package logging

// Replaces a secret value. Searchable on purpose: counting these tells you
// how often callers try to log credentials.
const Redacted = "[redacted]"

// Replaces a log message that contained a credential shape. The line is
// still emitted — dropping it entirely would hide the fact that something
// tried to log a secret, which is itself worth knowing.
//
// SuppressedMessage replaces such a message.
const SuppressedMessage = "log line suppressed: it contained a credential-shaped literal"

// Substrings that classify a log key as secret-bearing.
//
// Substring matching is deliberately broad: a new provider's SDK will invent a
// field name nobody predicted, and over-redacting a field is recoverable while
// leaking a credential is not.
var denySubstrings = []string{
	"token",
	"secret",
	"password",
	"passwd",
	"authorization",
	"auth",
	"cookie",
	"ciphertext",
	"refresh",
	"credential",
	"signature",
	"bearer",
	"apikey",
	"dek",
	"key",
	"dsn",
}

// Keys rescued from the denylist. Checked first.
//
// This list is load-bearing: without it "key" alone eats idempotency_key and
// cache_key, and "auth" eats author. A test in each language ties it to the
// log_keys vocabulary above, so a new field name that the denylist would
// swallow fails the build rather than going quietly missing from your logs.
var allowExact = []string{
	"idempotency_key",
	"cache_key",
	"event_key",
	"key_id",
	"public_key",
	"kms_key_id",
	"price_book_key",
	"config_key",
	"session_id",
	"org_id",
	"project_id",
	"keyboard",
	"monkey_patch",
	"author",
	"authored_at",
	"authorized_at",
}

// Literal credential shapes, scanned for in the message text itself.
//
// This closes the one hole key matching cannot: a token interpolated into a
// message by a library we do not own, as in
// log.Printf("auth failed for token=%s", tok).
//
// Literal prefixes only — no regular expressions. Measured at ~172ns with zero
// allocations on a clean string in Go, which is cheap enough to run on every
// line.
//
// Task 2.13's gitd pre-receive secret scanner reads this same list.
var secretPrefixes = []string{
	// Stripe
	"sk_live_", "sk_test_", "whsec_", "rk_live_",
	// GitHub
	"ghp_", "gho_", "github_pat_",
	// Slack
	"xoxb-", "xoxp-",
	// AWS
	"AKIA", "ASIA",
	// Anthropic
	"sk-ant-",
	// Google
	"AIza", "ya29.",
	// GitLab
	"glpat-",
	// A JWT header, base64
	"eyJhbGciOi",
	// A PEM private key block
	"-----BEGIN ",
	// Connection strings, which carry a password inline
	"postgres://", "postgresql://", "redis://", "rediss://",
	"mysql://", "amqp://",
}
