"""Generated by scripts/gen_obs.py from packages/schema/observability.json. DO NOT EDIT.

Edit packages/schema/observability.json and run `make gen`.

The Go chassis is generated from the same document, so a value here is the
same value there by construction rather than by review.

Span attribute and baggage keys carrying the SPEC 17.3 tenancy tuple.

Dotted segments follow OTel convention: an entity's id gets its own segment,
as in service.instance.id, and snake_case is reserved for multi-word leaves.
So halyard.org.id, not halyard.org_id.
"""

from __future__ import annotations

from typing import Final

from . import logkey

# Span attribute keys.
SPAN_ORG_ID: Final = "halyard.org.id"
SPAN_PROJECT_ID: Final = "halyard.project.id"
SPAN_SESSION_ID: Final = "halyard.session.id"
SPAN_TURN: Final = "halyard.turn"
SPAN_REQUEST_ID: Final = "halyard.request.id"
SPAN_ERROR_CODE: Final = "halyard.error.code"
SPAN_STREAM_KIND: Final = "halyard.stream.kind"

# Baggage member keys.
# Identical strings to the span attributes, named separately so a future
# divergence is expressible without a silent rename.
BAGGAGE_ORG_ID: Final = "halyard.org.id"
BAGGAGE_PROJECT_ID: Final = "halyard.project.id"
BAGGAGE_SESSION_ID: Final = "halyard.session.id"
BAGGAGE_TURN: Final = "halyard.turn"

# Each baggage member paired with the span attribute it becomes locally.
# The middleware that copies inbound baggage onto the current span iterates
# this, so a member added to the source document starts propagating without a
# second edit -- and the pairing is derived from a shared ident rather than
# from two lists that happen to be in the same order.
BAGGAGE_MEMBERS: Final[tuple[tuple[str, str], ...]] = (
    (BAGGAGE_ORG_ID, SPAN_ORG_ID),
    (BAGGAGE_PROJECT_ID, SPAN_PROJECT_ID),
    (BAGGAGE_SESSION_ID, SPAN_SESSION_ID),
    (BAGGAGE_TURN, SPAN_TURN),
)

# Baggage member -> the log field it is stamped into, so an inbound tenancy
# tuple reaches the log search as well as the trace. Paired by shared ident
# with log_keys, and gen_obs.py fails the build if a member has no log field.
BAGGAGE_LOG_FIELDS: Final[tuple[tuple[str, str], ...]] = (
    (BAGGAGE_ORG_ID, logkey.ORG_ID),
    (BAGGAGE_PROJECT_ID, logkey.PROJECT_ID),
    (BAGGAGE_SESSION_ID, logkey.SESSION_ID),
    (BAGGAGE_TURN, logkey.TURN),
)

__all__ = [
    "BAGGAGE_LOG_FIELDS",
    "BAGGAGE_MEMBERS",
    "BAGGAGE_ORG_ID",
    "BAGGAGE_PROJECT_ID",
    "BAGGAGE_SESSION_ID",
    "BAGGAGE_TURN",
    "SPAN_ERROR_CODE",
    "SPAN_ORG_ID",
    "SPAN_PROJECT_ID",
    "SPAN_REQUEST_ID",
    "SPAN_SESSION_ID",
    "SPAN_STREAM_KIND",
    "SPAN_TURN",
]
