"""Generated by scripts/gen_obs.py from packages/schema/observability.json. DO NOT EDIT.

Edit packages/schema/observability.json and run `make gen`.

The Go chassis is generated from the same document, so a value here is the
same value there by construction rather than by review.

The closed vocabulary of structured log field names.

It is closed so that a rename is one edit rather than a grep, and so that the
redaction audit test has something finite to iterate: every key here is
asserted not to be classified as a secret, which is what stops the denylist's
substring matching from silently swallowing a field a debugger needed.

Import the module, not the strings:

    from halyard_chassis.obs import logkey

    log.info("ready", extra={logkey.ADDR: addr})

logkey.ORG_ID here is logkey.OrgID in Go, from the same line of the same
document.
"""

from __future__ import annotations

from typing import Final

# Process identity.
SERVICE: Final = "service"
ENV: Final = "env"
VERSION: Final = "version"
COMMIT: Final = "commit"
INSTANCE: Final = "instance_id"

# Correlation.
# SPEC 17.3 wants a trace spanning five hops; these are the fields that let
# a log search join onto it.
REQUEST_ID: Final = "request_id"
TRACE_ID: Final = "trace_id"
SPAN_ID: Final = "span_id"
SAMPLED: Final = "trace_sampled"

# Tenancy.
# SPEC 17.3.
ORG_ID: Final = "org_id"
PROJECT_ID: Final = "project_id"
SESSION_ID: Final = "session_id"
TURN: Final = "turn"

# Failure.
ERROR_CODE: Final = "error_code"
ERR: Final = "error"
PANIC_VALUE: Final = "panic_value"
STACK: Final = "stack"

# HTTP.
# Route, never path: a raw path is unbounded cardinality and can carry a
# token or a user-chosen slug.
HTTP_METHOD: Final = "http_method"
HTTP_ROUTE: Final = "http_route"
HTTP_STATUS: Final = "http_status"
HTTP_BYTES: Final = "http_bytes"
DURATION_MS: Final = "duration_ms"
CLIENT_IP: Final = "client_ip"

# General.
COMPONENT: Final = "component"
REASON: Final = "reason"
PHASE: Final = "phase"
COUNT: Final = "count"

# Streams and shutdown.
STREAM_KIND: Final = "stream_kind"
STREAMS_OPEN: Final = "streams_open"
STREAMS_REMAINING: Final = "streams_remaining"
CLEAN: Final = "clean"

# Readiness.
PROBE: Final = "probe"
PROBE_STATE: Final = "probe_state"
PROBE_SINCE: Final = "probe_since"
LATENCY_MS: Final = "latency_ms"

# Boot.
ADDR: Final = "addr"
CONFIG_KEY: Final = "config_key"

# Every key in the vocabulary. The redaction audit test iterates it, so a key
# added to the source document is automatically covered.
LOG_KEYS: Final[tuple[str, ...]] = (
    SERVICE,
    ENV,
    VERSION,
    COMMIT,
    INSTANCE,
    REQUEST_ID,
    TRACE_ID,
    SPAN_ID,
    SAMPLED,
    ORG_ID,
    PROJECT_ID,
    SESSION_ID,
    TURN,
    ERROR_CODE,
    ERR,
    PANIC_VALUE,
    STACK,
    HTTP_METHOD,
    HTTP_ROUTE,
    HTTP_STATUS,
    HTTP_BYTES,
    DURATION_MS,
    CLIENT_IP,
    COMPONENT,
    REASON,
    PHASE,
    COUNT,
    STREAM_KIND,
    STREAMS_OPEN,
    STREAMS_REMAINING,
    CLEAN,
    PROBE,
    PROBE_STATE,
    PROBE_SINCE,
    LATENCY_MS,
    ADDR,
    CONFIG_KEY,
)

__all__ = [
    "ADDR",
    "CLEAN",
    "CLIENT_IP",
    "COMMIT",
    "COMPONENT",
    "CONFIG_KEY",
    "COUNT",
    "DURATION_MS",
    "ENV",
    "ERR",
    "ERROR_CODE",
    "HTTP_BYTES",
    "HTTP_METHOD",
    "HTTP_ROUTE",
    "HTTP_STATUS",
    "INSTANCE",
    "LATENCY_MS",
    "LOG_KEYS",
    "ORG_ID",
    "PANIC_VALUE",
    "PHASE",
    "PROBE",
    "PROBE_SINCE",
    "PROBE_STATE",
    "PROJECT_ID",
    "REASON",
    "REQUEST_ID",
    "SAMPLED",
    "SERVICE",
    "SESSION_ID",
    "SPAN_ID",
    "STACK",
    "STREAMS_OPEN",
    "STREAMS_REMAINING",
    "STREAM_KIND",
    "TRACE_ID",
    "TURN",
    "VERSION",
]
