"""Generated by scripts/gen_obs.py from packages/schema/observability.json. DO NOT EDIT.

Edit packages/schema/observability.json and run `make gen`.

The Go chassis is generated from the same document, so a value here is the
same value there by construction rather than by review.

The lists themselves. The matching logic that applies them is in
redaction.py, which is hand-written because it is logic rather than data.
"""

from __future__ import annotations

from typing import Final

# Replaces a secret value. Searchable on purpose: counting these tells you
# how often callers try to log credentials.
REDACTED: Final = "[redacted]"

# Replaces a log message that contained a credential shape. The line is
# still emitted — dropping it entirely would hide the fact that something
# tried to log a secret, which is itself worth knowing.
SUPPRESSED_MESSAGE: Final = "log line suppressed: it contained a credential-shaped literal"

# Substrings that classify a log key as secret-bearing.
#
# Substring matching is deliberately broad: a new provider's SDK will invent a
# field name nobody predicted, and over-redacting a field is recoverable while
# leaking a credential is not.
DENY_SUBSTRINGS: Final[tuple[str, ...]] = (
    "token",
    "secret",
    "password",
    "passwd",
    "authorization",
    "auth",
    "cookie",
    "ciphertext",
    "refresh",
    "credential",
    "signature",
    "bearer",
    "apikey",
    "dek",
    "key",
    "dsn",
)

# Keys rescued from the denylist. Checked first.
#
# This list is load-bearing: without it "key" alone eats idempotency_key and
# cache_key, and "auth" eats author. A test in each language ties it to the
# log_keys vocabulary above, so a new field name that the denylist would
# swallow fails the build rather than going quietly missing from your logs.
ALLOW_EXACT: Final[frozenset[str]] = frozenset(
    (
        "idempotency_key",
        "cache_key",
        "event_key",
        "key_id",
        "public_key",
        "kms_key_id",
        "price_book_key",
        "config_key",
        "session_id",
        "org_id",
        "project_id",
        "keyboard",
        "monkey_patch",
        "author",
        "authored_at",
        "authorized_at",
    )
)

# Literal credential shapes, scanned for in the message text itself.
#
# This closes the one hole key matching cannot: a token interpolated into a
# message by a library we do not own, as in
# log.Printf("auth failed for token=%s", tok).
#
# Literal prefixes only — no regular expressions. Measured at ~172ns with zero
# allocations on a clean string in Go, which is cheap enough to run on every
# line.
#
# Task 2.13's gitd pre-receive secret scanner reads this same list.
SECRET_PREFIXES: Final[tuple[str, ...]] = (
    # Stripe
    "sk_live_",
    "sk_test_",
    "whsec_",
    "rk_live_",
    # GitHub
    "ghp_",
    "gho_",
    "github_pat_",
    # Slack
    "xoxb-",
    "xoxp-",
    # AWS
    "AKIA",
    "ASIA",
    # Anthropic
    "sk-ant-",
    # Google
    "AIza",
    "ya29.",
    # GitLab
    "glpat-",
    # A JWT header, base64
    "eyJhbGciOi",
    # A PEM private key block
    "-----BEGIN ",
    # Connection strings, which carry a password inline
    "postgres://",
    "postgresql://",
    "redis://",
    "rediss://",
    "mysql://",
    "amqp://",
)

__all__ = [
    "ALLOW_EXACT",
    "DENY_SUBSTRINGS",
    "REDACTED",
    "SECRET_PREFIXES",
    "SUPPRESSED_MESSAGE",
]
