// Code generated by scripts/gen_obs.py; DO NOT EDIT.
// Edit packages/schema/observability.json and run `make gen`.
//
// Span attribute and baggage keys carrying the SPEC 17.3 tenancy tuple.
//
// Dotted segments follow OTel convention: an entity's id gets its own segment,
// as in service.instance.id, and snake_case is reserved for multi-word leaves.
// So halyard.org.id, not halyard.org_id.

package telemetry

import "go.opentelemetry.io/otel/attribute"

// Span attribute keys.
const (
	KeyOrgID      = attribute.Key("halyard.org.id")
	KeyProjectID  = attribute.Key("halyard.project.id")
	KeySessionID  = attribute.Key("halyard.session.id")
	KeyTurn       = attribute.Key("halyard.turn")
	KeyRequestID  = attribute.Key("halyard.request.id")
	KeyErrorCode  = attribute.Key("halyard.error.code")
	KeyStreamKind = attribute.Key("halyard.stream.kind")
)

// Baggage member keys.
// Identical strings to the span attributes, named separately so a future
// divergence is expressible without a silent rename.
const (
	BaggageOrgID     = "halyard.org.id"
	BaggageProjectID = "halyard.project.id"
	BaggageSessionID = "halyard.session.id"
	BaggageTurn      = "halyard.turn"
)
