#!/usr/bin/env bash
# Regenerate every language binding from packages/schema.
#
# SPEC 0 rule 2: the schemas are the single source of truth, and TypeScript, Go
# and Python are derived from them. Never hand-write the same type twice.
#
# Output is committed, not ignored, for two reasons: it lets CI diff a fresh
# generation against the tree to prove the two agree (`make gen-check`), and it
# means building a service does not require five code generators to be
# installed.
#
# This script must be deterministic. Anything that varies between runs — a
# timestamp, a map iteration order — turns the drift check into a coin flip
# that reviewers learn to re-run until it passes.
set -euo pipefail
cd "$(dirname "$0")/.."

SCHEMA=packages/schema
GEN=$SCHEMA/gen
TOOLS=$SCHEMA/tools
MODULE=github.com/anasatwork01/cofound/packages/schema
COMMON_PKG=$MODULE/gen/go/common

# JSON Schema documents, and the identifiers each maps to per language.
#            file                             go pkg        python module          ts file
JSON_DOCS=(
  "common.schema.json                         common        common                 common"
  "agent-events.schema.json                   agentevents   agent_events           agent-events"
  "capability-manifest.schema.json            capability    capability_manifest    capability-manifest"
  "meters.schema.json                         meters        meters                 meters"
)
#            file                    go pkg        python module    ts file
OPENAPI_DOCS=(
  "sandboxd.openapi.yaml             sandboxdapi   sandboxd_api     sandboxd-api"
  "api.openapi.yaml                  apiv1         api_v1           api-v1"
)

say() { printf '  %s\n' "$1"; }

# Regenerate from empty so a deleted schema takes its bindings with it — but
# keep gen/go/go.mod and gen/go/go.sum, which are checked-in infrastructure
# rather than generated output.
#
# They used to be rewritten here and reconciled with `go mod tidy`. That was
# wrong twice over: tidy needs the network, and with no require lines to pin
# against it resolves the *latest* version of each dependency, so a new release
# of oapi-codegen's runtime would fail the drift check on an unrelated pull
# request. Exactly the coin flip this script's header warns about.
#
# A schema change that introduces a new import now fails at `go build` with a
# message naming the missing module, which is a better place to find out.
rm -rf "$GEN/python" "$GEN/typescript" "$GEN/README.md"
find "$GEN/go" -mindepth 1 -maxdepth 1 -type d -exec rm -rf {} +
mkdir -p "$GEN/go" "$GEN/python/halyard_schema" "$GEN/typescript"

if [ ! -f "$GEN/go/go.mod" ]; then
  echo "error: $GEN/go/go.mod is missing. It is checked in, not generated." >&2
  exit 1
fi

# ------------------------------------------------------------------ go
say "go"
for row in "${JSON_DOCS[@]}"; do
  read -r doc pkg _ _ <<<"$row"
  mkdir -p "$GEN/go/$pkg"
  (cd "$TOOLS" && go tool go-jsonschema \
    --package "$pkg" \
    --output "../gen/go/$pkg/$pkg.gen.go" \
    "../$doc")
  say "    $pkg"
done

for row in "${OPENAPI_DOCS[@]}"; do
  read -r doc pkg _ _ <<<"$row"
  mkdir -p "$GEN/go/$pkg"
  (cd "$TOOLS" && go tool oapi-codegen \
    -generate types \
    -package "$pkg" \
    -import-mapping="./common.schema.json:$COMMON_PKG" \
    -o "../gen/go/$pkg/$pkg.gen.go" \
    "../$doc")
  say "    $pkg"
done

gofmt -w "$GEN/go"

# ------------------------------------------------------------------ python
say "python"
DMC_ARGS=(
  --output-model-type pydantic_v2.BaseModel
  --target-python-version 3.12
  --use-standard-collections
  --use-union-operator
  --use-title-as-name
  # Emit Annotated[str, Field(pattern=...)] rather than constr(...). With
  # `from __future__ import annotations` in the header, every annotation is a
  # string, and a bare constr() call inside one cannot be resolved when pydantic
  # builds the class — the model raises "is not fully defined" on first use.
  # Without this flag the generated models are unusable, which no test that
  # merely imports them would notice.
  --use-annotated
  # Without this every run rewrites a timestamp header and the drift check
  # fails on an unchanged schema.
  --disable-timestamp
  --formatters ruff-format
)
for row in "${JSON_DOCS[@]}" ; do
  read -r doc _ mod _ <<<"$row"
  uv run --quiet datamodel-codegen \
    --input "$SCHEMA/$doc" --input-file-type jsonschema \
    --output "$GEN/python/halyard_schema/$mod.py" "${DMC_ARGS[@]}"
  say "    $mod"
done
for row in "${OPENAPI_DOCS[@]}"; do
  read -r doc _ mod _ <<<"$row"
  uv run --quiet datamodel-codegen \
    --input "$SCHEMA/$doc" --input-file-type openapi \
    --output "$GEN/python/halyard_schema/$mod.py" "${DMC_ARGS[@]}"
  say "    $mod"
done
cat > "$GEN/python/halyard_schema/__init__.py" <<'EOF'
"""Generated by scripts/gen.sh. Edit packages/schema instead.

Importable as halyard_schema because packages/schema/pyproject.toml declares it
as a uv workspace member: the Python chassis renders wire errors with
halyard_schema.common.Error, and a module tree loaded by file path cannot be a
runtime dependency of anything.
"""
EOF
# PEP 561: without this, mypy in another package treats every import from
# halyard_schema as Any and the generated models stop checking anything.
touch "$GEN/python/halyard_schema/py.typed"

# ------------------------------------------------------------------ typescript
say "typescript"
for row in "${JSON_DOCS[@]}"; do
  read -r doc _ _ ts <<<"$row"
  npx --no-install json2ts \
    --input "$SCHEMA/$doc" \
    --output "$GEN/typescript/$ts.ts" \
    --cwd "$SCHEMA" \
    --additionalProperties false >/dev/null
  say "    $ts.ts"
done
for row in "${OPENAPI_DOCS[@]}"; do
  read -r doc _ _ ts <<<"$row"
  npx --no-install openapi-typescript "$SCHEMA/$doc" \
    -o "$GEN/typescript/$ts.ts" >/dev/null 2>&1
  say "    $ts.ts"
done

# ------------------------------------------------- observability vocabulary
# observability.json is deliberately absent from JSON_DOCS above: nothing
# serialises a document of that shape, so generating model types from it would
# produce dead code. What it needs instead is constants, in both languages, and
# those are emitted straight into the packages that own the identifiers rather
# than into gen/ — logkey.Service has to stay logkey.Service.
#
# Nothing is removed first. These four paths are rewritten in full on every run,
# and deleting them before regenerating would leave the tree missing files the
# Go build needs if the generator then failed.
say "observability"
uv run --quiet python scripts/gen_obs.py
gofmt -w $(./scripts/gen_obs.py --outputs | grep '\.go$')
uv run --quiet ruff format --quiet $(./scripts/gen_obs.py --outputs | grep '\.py$')

cat > "$GEN/README.md" <<'EOF'
# Generated bindings — do not edit

Every file here is produced by `scripts/gen.sh` from the schemas in
`packages/schema`. Editing one is pointless: the next `make gen` overwrites it,
and `make gen-check` fails the build in the meantime.

Change the schema, run `make gen`, and commit both together.

These are committed rather than ignored so that CI can prove the tree matches
the schemas, and so that building a service does not require five code
generators to be installed.

**Two exceptions:** `go/go.mod` and `go/go.sum` are checked in and
hand-maintained. `scripts/gen.sh` preserves them, because re-resolving those
versions on every run would make the drift check fail whenever a dependency
published a release. If generated code gains a new import, `go build` names the
missing module.
EOF
say "done"
