#!/usr/bin/env python3
"""Compile packages/schema/observability.json into Go and Python constants.

Called by scripts/gen.sh. See that script's header for why generated output is
committed rather than ignored.

Two properties matter here and are easy to lose:

  * Determinism. Nothing is sorted, nothing is timestamped, and iteration order
    comes from the JSON document. A generator whose output varies between runs
    turns `make gen-check` into a coin flip that reviewers learn to re-run.

  * The prose travels. The redaction lists are security-critical and the
    reasoning behind each one is the only thing that stops a future reader from
    "tidying" them. So `doc` fields are rendered as comments into every
    language, and the generated files read like hand-written ones.

Unlike the rest of scripts/gen.sh, the output does not live under
packages/schema/gen. It is emitted directly into the package that owns the
identifiers -- logkey.Service must stay logkey.Service, and routing it through
a generated module would either churn every call site or add an alias layer
that can itself go stale. `make gen-check` diffs these paths too.
"""

from __future__ import annotations

import json
import re
import sys
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "packages/schema/observability.json"
SOURCE_REL = "packages/schema/observability.json"

GO_LOGKEY = ROOT / "packages/chassis/logkey/keys.gen.go"
GO_LOGGING = ROOT / "packages/chassis/logging/vocab.gen.go"
GO_TELEMETRY = ROOT / "packages/chassis/telemetry/keys.gen.go"
PY_DIR = ROOT / "packages/pychassis/src/halyard_chassis/obs"
PY_LOGKEY = PY_DIR / "logkey.py"
PY_VOCAB = PY_DIR / "vocab.py"
PY_ATTRS = PY_DIR / "attrs.py"

# Every path this script writes. scripts/gen.sh reads this list via --outputs so
# the two cannot disagree about what `make gen-check` should be diffing.
OUTPUTS = (GO_LOGKEY, GO_LOGGING, GO_TELEMETRY, PY_LOGKEY, PY_VOCAB, PY_ATTRS)


# Comment text wraps to this width. 74 leaves room for both "// " and "# " and
# still lands inside Go's conventional 80 columns and ruff's line-length of 100.
COMMENT_WIDTH = 74


def lines(doc: str | list[str] | None) -> list[str]:
    """Normalise a `doc` field to a list of comment lines.

    A string is prose and gets wrapped; an array is already-wrapped lines and is
    preserved verbatim, blank elements included. That distinction is why authors
    of observability.json do not have to count columns for a one-line note, and
    why a carefully laid-out multi-paragraph block does not get reflowed into a
    single wall of text.
    """
    if doc is None:
        return []
    if isinstance(doc, list):
        return list(doc)
    return textwrap.wrap(doc, width=COMMENT_WIDTH) or [""]


def go_comment(doc: str | list[str] | None, indent: str = "") -> list[str]:
    return [f"{indent}//{' ' + ln if ln else ''}" for ln in lines(doc)]


def py_comment(doc: str | list[str] | None, indent: str = "") -> list[str]:
    return [f"{indent}#{' ' + ln if ln else ''}" for ln in lines(doc)]


def go_str(value: str) -> str:
    """A Go string literal. JSON and Go agree on escaping for these values."""
    return json.dumps(value)


def py_str(value: str) -> str:
    return json.dumps(value)


_SPLIT_ACRONYM = re.compile(r"([A-Z]+)([A-Z][a-z])")
_SPLIT_WORD = re.compile(r"([a-z0-9])([A-Z])")


def screaming(ident: str) -> str:
    """PascalCase -> SCREAMING_SNAKE_CASE, acronym-aware.

    OrgID -> ORG_ID, HTTPMethod -> HTTP_METHOD, DurationMS -> DURATION_MS.
    A naive ident.upper() gives ORGID and HTTPMETHOD, which read as typos.
    """
    s = _SPLIT_ACRONYM.sub(r"\1_\2", ident)
    s = _SPLIT_WORD.sub(r"\1_\2", s)
    return s.upper()


GENERATED_BY = f"Generated by scripts/gen_obs.py from {SOURCE_REL}. DO NOT EDIT."
EDIT_INSTEAD = f"Edit {SOURCE_REL} and run `make gen`."


def go_header(package: str, doc: str | list[str] | None = None) -> list[str]:
    out = ["// Code generated by scripts/gen_obs.py; DO NOT EDIT.", f"// {EDIT_INSTEAD}", "//"]
    out += go_comment(doc)
    out += ["", f"package {package}", ""]
    return out


def emit_go_logkey(d: dict) -> str:
    out = go_header("logkey", d["log_keys"]["doc"])
    all_groups: list[list[str]] = []
    for group in d["log_keys"]["groups"]:
        out.append(f"// {group['name']}.")
        out += go_comment(group.get("doc"))
        out.append("const (")
        for k in group["keys"]:
            out.append(f"\t{k['ident']} = {go_str(k['key'])}")
        out += [")", ""]
        all_groups.append([k["ident"] for k in group["keys"]])

    out += [
        "// All returns every key in the vocabulary. The redaction audit test iterates",
        "// it, so a key added to the source document is automatically covered.",
        "func All() []string {",
        "\treturn []string{",
    ]
    for idents in all_groups:
        out.append("\t\t" + ", ".join(idents) + ",")
    out += ["\t}", "}", ""]
    return "\n".join(out)


def emit_go_logging(d: dict) -> str:
    red = d["redaction"]
    consts = d["constants"]
    out = go_header(
        "logging",
        [
            "This file holds the vocabulary only. The handler that applies it, and the",
            "reasoning for wrapping slog.Handler rather than using ReplaceAttr, are in",
            "redact.go.",
        ],
    )

    out += go_comment(consts["redacted"]["doc"])
    out += [
        f"const Redacted = {go_str(consts['redacted']['value'])}",
        "",
    ]
    out += go_comment(consts["suppressed_message"]["doc"])
    out += [
        "//",
        "// SuppressedMessage replaces such a message.",
        f"const SuppressedMessage = {go_str(consts['suppressed_message']['value'])}",
        "",
    ]

    out += go_comment(red["deny_substrings"]["doc"])
    out.append("var denySubstrings = []string{")
    for v in red["deny_substrings"]["values"]:
        out.append(f"\t{go_str(v)},")
    out += ["}", ""]

    out += go_comment(red["allow_exact"]["doc"])
    out.append("var allowExact = []string{")
    for v in red["allow_exact"]["values"]:
        out.append(f"\t{go_str(v)},")
    out += ["}", ""]

    out += go_comment(red["secret_prefixes"]["doc"])
    out.append("var secretPrefixes = []string{")
    for group in red["secret_prefixes"]["groups"]:
        out.append(f"\t// {group['name']}")
        # Pack several per line, but stop before the line gets wide enough that a
        # reviewer has to scroll sideways to see what is on the redaction list.
        row: list[str] = []
        for v in group["values"]:
            row.append(go_str(v))
            if len(", ".join(row)) > 52:
                out.append("\t" + ", ".join(row) + ",")
                row = []
        if row:
            out.append("\t" + ", ".join(row) + ",")
    out += ["}", ""]
    return "\n".join(out)


def emit_go_telemetry(d: dict) -> str:
    tk = d["trace_keys"]
    out = go_header("telemetry", tk["doc"])
    out.append("// Span attribute keys.")
    out.append("const (")
    for k in tk["span_attributes"]:
        out.append(f"\tKey{k['ident']} = attribute.Key({go_str(k['key'])})")
    out += [")", ""]

    out += ["// Baggage member keys."]
    out += go_comment(tk["baggage"]["doc"])
    out.append("const (")
    for k in tk["baggage"]["members"]:
        out.append(f"\tBaggage{k['ident']} = {go_str(k['key'])}")
    out += [")", ""]

    # The import goes last so it can be omitted when nothing needs it; gofmt
    # would not remove an unused one, it would just fail to compile.
    body = "\n".join(out)
    if "attribute.Key(" in body:
        body = body.replace(
            "\n// Span attribute keys.",
            '\nimport "go.opentelemetry.io/otel/attribute"\n\n// Span attribute keys.',
            1,
        )
    return body


def py_header(doc: str | list[str] | None) -> list[str]:
    return [
        f'"""{GENERATED_BY}',
        "",
        EDIT_INSTEAD,
        "",
        "The Go chassis is generated from the same document, so a value here is the",
        "same value there by construction rather than by review.",
        *(["", *lines(doc)] if doc else []),
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import Final",
        "",
    ]


def py_all(names: list[str]) -> list[str]:
    """__all__ is generated too. A hand-maintained one is a list that silently
    stops exporting the newest constant."""
    out = ["", "__all__ = ["]
    out += [f'    "{n}",' for n in sorted(names)]
    out.append("]")
    return out


def emit_py_logkey(d: dict) -> str:
    lk = d["log_keys"]
    out = py_header(
        [
            *lines(lk["doc"]),
            "",
            "Import the module, not the strings:",
            "",
            "    from halyard_chassis.obs import logkey",
            "",
            '    log.info("ready", extra={logkey.ADDR: addr})',
            "",
            "logkey.ORG_ID here is logkey.OrgID in Go, from the same line of the same",
            "document.",
        ]
    )
    names: list[str] = []
    for group in lk["groups"]:
        out.append(f"# {group['name']}.")
        out += py_comment(group.get("doc"))
        for k in group["keys"]:
            name = screaming(k["ident"])
            out.append(f"{name}: Final = {py_str(k['key'])}")
            names.append(name)
        out.append("")

    out += [
        "# Every key in the vocabulary. The redaction audit test iterates it, so a key",
        "# added to the source document is automatically covered.",
        "LOG_KEYS: Final[tuple[str, ...]] = (",
    ]
    out += [f"    {n}," for n in names]
    out.append(")")
    out += py_all([*names, "LOG_KEYS"])
    return "\n".join(out)


def emit_py_vocab(d: dict) -> str:
    red = d["redaction"]
    consts = d["constants"]
    out = py_header(
        [
            "The lists themselves. The matching logic that applies them is in",
            "redaction.py, which is hand-written because it is logic rather than data.",
        ]
    )

    out += py_comment(consts["redacted"]["doc"])
    out += [f"REDACTED: Final = {py_str(consts['redacted']['value'])}", ""]
    out += py_comment(consts["suppressed_message"]["doc"])
    out += [f"SUPPRESSED_MESSAGE: Final = {py_str(consts['suppressed_message']['value'])}", ""]

    out += py_comment(red["deny_substrings"]["doc"])
    out.append("DENY_SUBSTRINGS: Final[tuple[str, ...]] = (")
    out += [f"    {py_str(v)}," for v in red["deny_substrings"]["values"]]
    out += [")", ""]

    out += py_comment(red["allow_exact"]["doc"])
    # A frozenset, not a tuple: this one is only ever asked "is this key in it",
    # and the Go side's linear scan is over a list it also only ever asks that of.
    out.append("ALLOW_EXACT: Final[frozenset[str]] = frozenset(")
    out.append("    (")
    out += [f"        {py_str(v)}," for v in red["allow_exact"]["values"]]
    out += ["    )", ")", ""]

    out += py_comment(red["secret_prefixes"]["doc"])
    out.append("SECRET_PREFIXES: Final[tuple[str, ...]] = (")
    for group in red["secret_prefixes"]["groups"]:
        out.append(f"    # {group['name']}")
        out += [f"    {py_str(v)}," for v in group["values"]]
    out.append(")")
    out += py_all(
        ["REDACTED", "SUPPRESSED_MESSAGE", "DENY_SUBSTRINGS", "ALLOW_EXACT", "SECRET_PREFIXES"]
    )
    return "\n".join(out)


def emit_py_attrs(d: dict) -> str:
    tk = d["trace_keys"]
    out = py_header(tk["doc"])
    names: list[str] = []

    out.append("# Span attribute keys.")
    span_by_ident = {}
    for k in tk["span_attributes"]:
        name = f"SPAN_{screaming(k['ident'])}"
        out.append(f"{name}: Final = {py_str(k['key'])}")
        names.append(name)
        span_by_ident[k["ident"]] = name
    out.append("")

    out.append("# Baggage member keys.")
    out += py_comment(tk["baggage"]["doc"])
    bag: list[tuple[str, str]] = []
    for k in tk["baggage"]["members"]:
        name = f"BAGGAGE_{screaming(k['ident'])}"
        out.append(f"{name}: Final = {py_str(k['key'])}")
        names.append(name)
        bag.append((name, span_by_ident[k["ident"]]))
    out.append("")

    out += [
        "# Each baggage member paired with the span attribute it becomes locally.",
        "# The middleware that copies inbound baggage onto the current span iterates",
        "# this, so a member added to the source document starts propagating without a",
        "# second edit -- and the pairing is derived from a shared ident rather than",
        "# from two lists that happen to be in the same order.",
        "BAGGAGE_MEMBERS: Final[tuple[tuple[str, str], ...]] = (",
    ]
    out += [f"    ({b}, {s})," for b, s in bag]
    out.append(")")

    # Baggage member -> log field name, for the middleware that stamps inbound
    # tenancy onto the log context. Both come from the same `ident`, so the
    # pairing is derived rather than written down twice in two vocabularies.
    log_by_ident = {
        k["ident"]: screaming(k["ident"]) for g in d["log_keys"]["groups"] for k in g["keys"]
    }
    pairs = [
        (f"BAGGAGE_{screaming(k['ident'])}", log_by_ident[k["ident"]])
        for k in tk["baggage"]["members"]
        if k["ident"] in log_by_ident
    ]
    missing = [k["ident"] for k in tk["baggage"]["members"] if k["ident"] not in log_by_ident]
    if missing:
        raise SystemExit(
            f"gen_obs: baggage members {missing} have no log_keys entry with the same "
            "ident, so there is no log field to stamp them into. Add one, or the "
            "tenancy tuple reaches spans but not logs."
        )
    out += [
        "",
        "# Baggage member -> the log field it is stamped into, so an inbound tenancy",
        "# tuple reaches the log search as well as the trace. Paired by shared ident",
        "# with log_keys, and gen_obs.py fails the build if a member has no log field.",
        "BAGGAGE_LOG_FIELDS: Final[tuple[tuple[str, str], ...]] = (",
    ]
    out += [f"    ({b}, logkey.{lk})," for b, lk in pairs]
    out.append(")")

    body = "\n".join(out + py_all([*names, "BAGGAGE_MEMBERS", "BAGGAGE_LOG_FIELDS"]))
    # The module, not the names: `logkey.ORG_ID` beside `BAGGAGE_ORG_ID` keeps
    # the two vocabularies visibly distinct at every call site.
    return body.replace(
        "from typing import Final\n",
        "from typing import Final\n\nfrom . import logkey\n",
        1,
    )


def main(argv: list[str]) -> int:
    if "--outputs" in argv:
        # scripts/gen.sh asks for the paths so its clean-up step and the drift
        # check cover exactly what this script writes.
        for p in OUTPUTS:
            print(p.relative_to(ROOT))
        return 0

    doc = json.loads(SOURCE.read_text())
    for path, text in (
        (GO_LOGKEY, emit_go_logkey(doc)),
        (GO_LOGGING, emit_go_logging(doc)),
        (GO_TELEMETRY, emit_go_telemetry(doc)),
        (PY_LOGKEY, emit_py_logkey(doc)),
        (PY_VOCAB, emit_py_vocab(doc)),
        (PY_ATTRS, emit_py_attrs(doc)),
    ):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text if text.endswith("\n") else text + "\n")
        print(f"    {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
